# Lumenera USB camera models first stage firmware loader Makefile

#luldr	infinity1-2b	Makefile	LULDR_PID		=	4A2
obj-$(CONFIG_INFINITY1_2B) += infinity1-2b/

#luldr	infinity1-5	Makefile	LULDR_PID		=	1AC
obj-$(CONFIG_INFINITY1_5) += infinity1-5/

#luldr	infinity1-6	Makefile	LULDR_PID		=	1A6
obj-$(CONFIG_INFINITY1_6) += infinity1-6/

#luldr	infinity1	Makefile	LULDR_PID		=	0A1
obj-$(CONFIG_INFINITY1) += infinity1/

#luldr	infinity2-1	Makefile	LULDR_PID		=	1A2
obj-$(CONFIG_INFINITY2_1) += infinity2-1/

#luldr	infinity2-2	Makefile	LULDR_PID		=	1A7
obj-$(CONFIG_INFINITY2_2) += infinity2-2/

#luldr	infinity2-5	Makefile	LULDR_PID		=	4AE
obj-$(CONFIG_INFINITY2_5) += infinity2-5/

#luldr	infinity3-1	Makefile	LULDR_PID		=	1A5
obj-$(CONFIG_INFINITY3_1) += infinity3-1/

#luldr	infinity3-1u	Makefile	LULDR_PID		=	1AF
obj-$(CONFIG_INFINITY3_1U) += infinity3-1u/

#luldr	infinity3	Makefile	LULDR_PID		=	0A3
obj-$(CONFIG_INFINITY3) += infinity3/

#luldr	infinity4-11	Makefile	LULDR_PID		=	1A8
obj-$(CONFIG_INFINITY4_11) += infinity4-11/

#luldr	infinity4-4	Makefile	LULDR_PID		=	1AB
obj-$(CONFIG_INFINITY4_4) += infinity4-4/

#luldr	infinitylite	Makefile	LULDR_PID		=	3AD
obj-$(CONFIG_INFINITYLITE) += infinitylite/

#luldr	lc080	Makefile	LULDR_PID		=	384
obj-$(CONFIG_LC080) += lc080/

#luldr	lc170	Makefile	LULDR_PID		=	39E
obj-$(CONFIG_LC170) += lc170/

#luldr	lc270	Makefile	LULDR_PID		=	38D
obj-$(CONFIG_LC270) += lc270/

#luldr	lc370	Makefile	LULDR_PID		=	38B
obj-$(CONFIG_LC370) += lc370/

#luldr	lm070	Makefile	LULDR_PID		=	28C
obj-$(CONFIG_LM070) += lm070/

#luldr	lm080	Makefile	LULDR_PID		=	284
obj-$(CONFIG_LM080) += lm080/

#luldr	lm11050	Makefile	LULDR_PID		=	2C8
obj-$(CONFIG_LM11050) += lm11050/

#luldr	lm130	Makefile	LULDR_PID		=	29A
obj-$(CONFIG_LM130) += lm130/

#luldr	lm160	Makefile	LULDR_PID		=	28A
obj-$(CONFIG_LM160) += lm160/

#luldr	lu070	Makefile	LULDR_PID		=	08C
obj-$(CONFIG_LU070) += lu070/

#luldr	lu080	Makefile	LULDR_PID		=	085
obj-$(CONFIG_LU080) += lu080/

#luldr	lu100	Makefile	LULDR_PID		=	092
obj-$(CONFIG_LU100) += lu100/

#luldr	lu120	Makefile	LULDR_PID		=	096
obj-$(CONFIG_LU120) += lu120/

#luldr	lu130	Makefile	LULDR_PID		=	09A
obj-$(CONFIG_LU130) += lu130/

#luldr	lu170b	Makefile	LULDR_PID		=	099
obj-$(CONFIG_LU170B) += lu170b/

#luldr	lu170	Makefile	LULDR_PID		=	09E
obj-$(CONFIG_LU170) += lu170/

#luldr	lu200	Makefile	LULDR_PID		=	097
obj-$(CONFIG_LU200) += lu200/

#luldr	lu270	Makefile	LULDR_PID		=	08D
obj-$(CONFIG_LU270) += lu270/

#luldr	lu370	Makefile	LULDR_PID		=	08B
obj-$(CONFIG_LU370) += lu370/

#luldr	lw070	Makefile	LULDR_PID		=	18C
obj-$(CONFIG_LW070) += lw070/

#luldr	lw11050	Makefile	LULDR_PID		=	1C8
obj-$(CONFIG_LW11050) += lw11050/

#luldr	lw110	Makefile	LULDR_PID		=	49f
obj-$(CONFIG_LW110) += lw110/

#luldr	lw130	Makefile	LULDR_PID		=	19A
obj-$(CONFIG_LW130) += lw130/

#luldr	lw16050	Makefile	LULDR_PID		=	1C9
obj-$(CONFIG_LW16050) += lw16050/

#luldr	lw160	Makefile	LULDR_PID		=	18A
obj-$(CONFIG_LW160) += lw160/

#luldr	lw230	Makefile	LULDR_PID		=	180
obj-$(CONFIG_LW230) += lw230/

#luldr	lw290	Makefile	LULDR_PID		=	1CD
obj-$(CONFIG_LW290) += lw290/

#luldr	lw450	Makefile	LULDR_PID		=	1C7
obj-$(CONFIG_LW450) += lw450/

#luldr	lw560	Makefile	LULDR_PID		=	4CE
obj-$(CONFIG_LW560) += lw560/

#luldr	lw570	Makefile	LULDR_PID		=	1C5
obj-$(CONFIG_LW570) += lw570/

#luldr	lw620	Makefile	LULDR_PID		=	186
obj-$(CONFIG_LW620) += lw620/

