# Makefile - driver build system
#
# Copyright (C) 2005 Lumenera
#
# Requires GNU Make

LUCAM_PREFIX := lw
LUCAM_PID := 49f
CAMERA_DEFS =

ifeq ($(src),)
src := $(CURDIR)
endif 

include $(src)/../lucam.mk
