# Lumenera USB camera models second stage firmware loader Makefile

#lucam	infinity1-2b	Makefile	LUCAM_PID		=	4A2
obj-$(CONFIG_INFINITY1_2B) += infinity1-2b/

#lucam	infinity1-5	Makefile	LUCAM_PID		=	1AC
obj-$(CONFIG_INFINITY1_5) += infinity1-5/

#lucam	infinity1-6	Makefile	LUCAM_PID		=	1A6
obj-$(CONFIG_INFINITY1_6) += infinity1-6/

#lucam	infinity1	Makefile	LUCAM_PID		=	0A1
obj-$(CONFIG_INFINITY1) += infinity1/

#lucam	infinity2-1	Makefile	LUCAM_PID		=	1A2
obj-$(CONFIG_INFINITY2_1) += infinity2-1/

#lucam	infinity2-2	Makefile	LUCAM_PID		=	1A7
obj-$(CONFIG_INFINITY2_2) += infinity2-2/

#lucam	infinity2-5	Makefile	LUCAM_PID		=	4AE
obj-$(CONFIG_INFINITY2_5) += infinity2-5/

#lucam	infinity3-1	Makefile	LUCAM_PID		=	1A5
obj-$(CONFIG_INFINITY3_1) += infinity3-1/

#lucam	infinity3-1u	Makefile	LUCAM_PID		=	1AF
obj-$(CONFIG_INFINITY3_1U) += infinity3-1u/

#lucam	infinity3	Makefile	LUCAM_PID		=	0A3
obj-$(CONFIG_INFINITY3) += infinity3/

#lucam	infinity4-11	Makefile	LUCAM_PID		=	1A8
obj-$(CONFIG_INFINITY4_11) += infinity4-11/

#lucam	infinity4-4	Makefile	LUCAM_PID		=	1AB
obj-$(CONFIG_INFINITY4_4) += infinity4-4/

#lucam	infinitylite	Makefile	LUCAM_PID		=	3AD
obj-$(CONFIG_INFINITYLITE) += infinitylite/

#lucam	lc080	Makefile	LUCAM_PID		=	384
obj-$(CONFIG_LC080) += lc080/

#lucam	lc170	Makefile	LUCAM_PID		=	39E
obj-$(CONFIG_LC170) += lc170/

#lucam	lc270	Makefile	LUCAM_PID		=	38D
obj-$(CONFIG_LC270) += lc270/

#lucam	lc370	Makefile	LUCAM_PID		=	38B
obj-$(CONFIG_LC370) += lc370/

#lucam	lm070	Makefile	LUCAM_PID		=	28C
obj-$(CONFIG_LM070) += lm070/

#lucam	lm080	Makefile	LUCAM_PID		=	284
obj-$(CONFIG_LM080) += lm080/

#lucam	lm11050	Makefile	LUCAM_PID		=	2C8
obj-$(CONFIG_LM11050) += lm11050/

#lucam	lm130	Makefile	LUCAM_PID		=	29A
obj-$(CONFIG_LM130) += lm130/

#lucam	lm160	Makefile	LUCAM_PID		=	28A
obj-$(CONFIG_LM160) += lm160/

#lucam	ltcamusb	Makefile	LUCAM_PID		=	usb
obj-$(CONFIG_LTCAMUSB) += ltcamusb/

#lucam	ltcamusb	Makefile	LUCAM_PID		=	usb
obj-$(CONFIG_LTCAMUSB) += ltcamusb/

#lucam	lu070	Makefile	LUCAM_PID		=	08C
obj-$(CONFIG_LU070) += lu070/

#lucam	lu080	Makefile	LUCAM_PID		=	085
obj-$(CONFIG_LU080) += lu080/

#lucam	lu100	Makefile	LUCAM_PID		=	092
obj-$(CONFIG_LU100) += lu100/

#lucam	lu120	Makefile	LUCAM_PID		=	096
obj-$(CONFIG_LU120) += lu120/

#lucam	lu130	Makefile	LUCAM_PID		=	09A
obj-$(CONFIG_LU130) += lu130/

#lucam	lu170b	Makefile	LUCAM_PID		=	099
obj-$(CONFIG_LU170B) += lu170b/

#lucam	lu170	Makefile	LUCAM_PID		=	09E
obj-$(CONFIG_LU170) += lu170/

#lucam	lu200	Makefile	LUCAM_PID		=	097
obj-$(CONFIG_LU200) += lu200/

#lucam	lu270	Makefile	LUCAM_PID		=	08D
obj-$(CONFIG_LU270) += lu270/

#lucam	lu370	Makefile	LUCAM_PID		=	08B
obj-$(CONFIG_LU370) += lu370/

#lucam	lw070	Makefile	LUCAM_PID		=	18C
obj-$(CONFIG_LW070) += lw070/

#lucam	lw11050	Makefile	LUCAM_PID		=	1C8
obj-$(CONFIG_LW11050) += lw11050/

#lucam	lw110	Makefile	LUCAM_PID		=	49f
obj-$(CONFIG_LW110) += lw110/

#lucam	lw130	Makefile	LUCAM_PID		=	19A
obj-$(CONFIG_LW130) += lw130/

#lucam	lw16050	Makefile	LUCAM_PID		=	1C9
obj-$(CONFIG_LW16050) += lw16050/

#lucam	lw160	Makefile	LUCAM_PID		=	18A
obj-$(CONFIG_LW160) += lw160/

#lucam	lw230	Makefile	LUCAM_PID		=	180
obj-$(CONFIG_LW230) += lw230/

#lucam	lw290	Makefile	LUCAM_PID		=	1CD
obj-$(CONFIG_LW290) += lw290/

#lucam	lw450	Makefile	LUCAM_PID		=	1C7
obj-$(CONFIG_LW450) += lw450/

#lucam	lw560	Makefile	LUCAM_PID		=	4CE
obj-$(CONFIG_LW560) += lw560/

#lucam	lw570	Makefile	LUCAM_PID		=	1C5
obj-$(CONFIG_LW570) += lw570/

#lucam	lw620	Makefile	LUCAM_PID		=	186
obj-$(CONFIG_LW620) += lw620/

