# Makefile - driver build system
#
# Copyright (C) 2005 Lumenera
#
# Requires GNU Make

LUCAM_PREFIX := lw
LUCAM_PID := 180
FPGA_FILE0 := $(src)/fpga0.bin
FPGA_FILE10 := $(src)/fpga10.bin


ifeq ($(src),)
src := $(CURDIR)
endif 

include $(src)/../lucam.mk

