/****************************************************
* This file is automaticaaly generated by appec.exe *
****************************************************/
#include "../driver.h"

//------------------------------------------------------

//------------------------------------------------------

//------------------------------------------------------

struct _FpgaList2 FpgasList[] = 
{
   {
      0x0384, // pid
      0x0000, // did
      NULL, // ptr to fpga desc list
      0, // count in fpga desc list
   },
};

int FpgasListCount = sizeof(FpgasList)/sizeof(FpgasList[0]);
